### ISSUE TITLE
Creation of multiple roles

### ISSUE THREAD

**Issue by d-korni** [climu/OSR-discord-bot#1]
At the moment we have one role for "looking for game" @lfg.

The idea was that we can create multiple roles for various channels (as we need them), to which people can sign up on. Then, when someone wants help from on of those groups, by summoning that group role of the bot, the bot will tag the people who are currently active in the role.

Example:
Some users have signed up to the role "!game_review"
I post a game in "game_discussion" channel and I want someone to help me review it.
My next step is to tell the bot "!help_review" and the bot will tag the members of "!game_review" role.
In this way, we avoid using @here, and people can members of their role for longer term (if the convention is that this role is not an instant response one).

It would work similarly for other roles, but perhaps some would be like the !LFG one, where people activate and deactivate as appropriate.

Current thoughts for roles:
**Channel - Role - Description**
game discussion - Reviewers - People that will be available to help others with reviews
tsumego - tsumegoers - When a new tsumego (as opposed to random discussions) is being posted, they can be tagged
all channels - ddk/sdk/dan - People can sign up to these roles so that they get relevant information. Then when a resource or problem particularly useful to these people is being posted, they can be tagged

This is just some I thought would be useful. We can of course add and remove as appropriate with feedback from the community.

**Comment by climu** [comment]
I really like this idea.

Are thinking that we should allow such commands only in a dedicated channel?

We should also think the naming of bot command for each role. I guess `!review`, `!tsumego`, `!dan/sdk/ddk.`

**Comment by climu** [comment]
I created roles on discord. pasting roles ids here:

- tusmegoers: 462186851747233793
- reviewers: 462187005602955266
- dan: 462186943221071872
- sdk: 462186975240388620
-ddk: 462187620156309514

Since it will be the same logic for each role I guess we should write a method that deals with it.
