### ISSUE TITLE
Delete user commands once bot replies?

### ISSUE THREAD

**Issue by d-korni** [climu/OSR-discord-bot#11]
When I opened discord, I saw a really nasty looking paeg with a bunch of random commands (usually !LFG followed by !whos_LFG straight away).

Just wondering, would it not be better to have the bot respond to the command and delete the user command, leaving the bot output?

Only caveat to that is that new members won't be able to see what command was used for this output, but surely it is easy enough to see all comands by typing !help.

**Comment by climu** [comment]
I see another downside with that: We cannot see who called the bot.

This could be fixed by adding the caller username or even tag in the answer message.

**Comment by d-korni** [comment]
Yes, I thought about that and adding the name would be best.
