### ISSUE TITLE
the time limit functionality doesn't seem to be working

### ISSUE THREAD

**Issue by alexmitrani** [climu/OSR-discord-bot#14]
today I entered !LFG 30 at 13:06 (chile time).  When at 13:48 someone else entered !LFG it said I was still looking for a game.  Did I enter the time limit wrong, or is it not working?

**Comment by d-korni** [comment]
It did work in the tests we've done, and also in Discord before. It might be related with some slag the bot had earlier today. @alexmitrani can you retry and see?

**Comment by climu** [comment]
I suspect it might be because I restarted the bot in the meantime.

I would suggest we wait this testing time when we update and restart the bot quite often to check on that afterwards.

**Comment by alexmitrani** [comment]
kj01a also commented on Discord that this wasn't working, last night.

**Comment by climu** [comment]
Yea, I saw. And I didn't updated the bot in the meantime so it appear to be a real bug :(

Anyway, for now we will fix the bot behaviour as soon as possible so users can start getting habits. Once it's done we will deal with this time thing.
