### ISSUE TITLE
Automatic addition to the LFG role when typing !whos_LFG

### ISSUE THREAD

**Issue by d-korni** [climu/OSR-discord-bot#2]
Under the assumption that someone is looking for a game when they type !whos_LFG, we could have that person being automatically (and silently) being added to the list.

**Comment by climu** [comment]
I am not sure about this assumption. Maybe users just want to check out of curiosity. I would suggest waiting to see if there is a demand for it.

**Comment by d-korni** [comment]
First demand for this came from Mushrooms in bot_commands channel ^^
