### ISSUE TITLE
Include challenger's rank in message to @players after !go

### ISSUE THREAD

**Issue by Razza99** [climu/OSR-discord-bot#22]
Currently when a player enters !go, a message goes out to @players:
  "Hey, `@player`! `@Razza` is looking for a game."

I propose it should include the players rank, eg:
  "Hey, `@player`! `@Razza` (OGS 9d | KGS 9d) is looking for a game."

Perhaps a little related, but separate to https://github.com/climu/OSR-discord-bot/issues/3

**Comment by climu** [comment]
Nice ranks!

That's a good and easy to implement idea.

note: I edited your comment to remove tagging github users **Razza** and **player**. If you guys read me, sorry.

**Comment by d-korni** [comment]
Issue tackled with #24 by Razza. 👍
