### ISSUE TITLE
!who and !list

### ISSUE THREAD

**Issue by Xandaros** [climu/OSR-discord-bot#28]
Many people seem to confuse the `!who` and `!whos` (or `!list`) command.

Part of the reason is probably that the commands are so similar and the commands were recently changed. However, I still feel like `!who lfg` seems like a reasonable command at first glance.

I'm not entirely sure how to avoid this confusion, so here's an idea. If somebody does `!who <user>` and `<user>` does not exist, in addition to the usual message, check if `<user>` is a valid role. If so, make the user aware of the `!list` command.

```
User: !who go
Bot: We have no such user in here. Sorry.

However, "go" is a valid role. Did you mean `!list go`?
```

**Comment by d-korni** [comment]
Indeed you are right, the `who` and `whos` are too similar and this is why we came up with the `list` command.
One of the issues is that the bot has had many changes lately, and it is not "officially" deployed yet. But I think your suggestion is good and makes sense, something we should perhaps try to implement.
