### ISSUE TITLE
Show full LFG list when being added to the list

### ISSUE THREAD

**Issue by d-korni** [climu/OSR-discord-bot#3]
When we type !LFG we get a not so useful message that we are looking for a game.
It would be better if we get a list of other users (and maybe their rank) that are looking for a game at the moment.

**Comment by climu** [comment]
The current message have the use of tagging the `LFG` role so all such users are notified.

I guess we could show the list of users but one can just type `!whos_LFG` to get that?

**Comment by d-korni** [comment]
My point is that, a user has to type both, and almost always they would type both. So why not skip the step, and when they type one command, the other one is issued at the same time.

**Comment by alexmitrani** [comment]
I agree with @d-korni, I would also like to know who else is looking and would rather type one command not two.

**Comment by climu** [comment]
then let's do it :)

**Comment by d-korni** [comment]
Issue tackled with #24 by Razza. 👍
