### ISSUE TITLE
Reaction is not working

### ISSUE THREAD

**Issue by climu** [climu/OSR-discord-bot#63]
![image](https://user-images.githubusercontent.com/2648653/48884884-8e65bc00-ee26-11e8-9d1c-87b341185771.png)
Nothing happens when clicking the reaction emote.

**Comment by d-korni** [comment]
It seems to be working fine on my end. Can you give an example of how to reproduce it?
I've tried with `!who korno` and `!who clime` and it works fine.

Note that if some time passes after the message was posted, the reaction will stop working.

**Comment by climu** [comment]
Tested too, and it actually works. I guess it was just the message being too old.
 Sorry for that.

Still we should understand what "old" means. My guess is if the bot restart we loose track of it since we have no database.
