### ISSUE TITLE
rename LFG

### ISSUE THREAD

**Issue by climu** [climu/OSR-discord-bot#7]
Following a suggestion in our discord server, maybe we should rename LFG.

Indeed it's not obvious that LFG stands for Looking For a Game.

It has been suggested a simple `!playme` command and a `@playme` role.

Not sure about that.

**Comment by alexmitrani** [comment]
I really like the bot but I find the commands are tricky and non-intuitive.  They are also case-sensitive.  whos_LFG is 12 key-presses on a smartphone (counting a long press as 2).  I suggest simpler commands such as:
!go - looking for a game
!nogo - not any more
!who - whos looking for a game?

**Comment by climu** [comment]
that's a good idea.

The issue with the `!who` command is that we might want to list other roles ([see this issue](https://github.com/climu/OSR-discord-bot/issues/1)).

Maybe a global command `!who` that would take an argument: `!who go`, `who dan`, `who review`...

**Comment by d-korni** [comment]
Are we agreeing on these commands then for looking for game?
!go !nogo and !who role

**Comment by climu** [comment]
sounds good to me. Maybe we can keep `LFG` as an alias for now since some users use it at first?

wondering if we should have a global `!no arg` command that would remove your from any role. Cause we will have `!nogo`, `!noddk` ...

Also thinking the `!who` command could take a user as argument and show his personal infos.

**Comment by alexmitrani** [comment]
perhaps the response to !who could list users in groups or with group information in brackets after their name?

**Comment by climu** [comment]
That is a neat idea here.

So far I am thinking `!who` for user and `!whos` for groups.

**Comment by alexmitrani** [comment]
Could it be !who goes instead of !whos go, please?  English speakers are taught from childhood that "who's" has an apostrophe.  Typing "whos" is unnatural to me.

**Comment by climu** [comment]
we can. But then we need something else to show one user infos.

At the moment you can also use `list`

**Comment by climu** [comment]
I think we are fix on the commands now:

`!go`, `!no go`, `!list go`, `!who user`.

If we all good I close this.

**Comment by d-korni** [comment]
I think we are for now, unless new need arises.
